# Alexa Prompts Language Constants

SKILL_NAME = "SKILL_NAME"
WELCOME_MESSAGE = "WELCOME_MESSAGE"
TEMPERATURE_MESSAGE = "TEMPERATURE_MESSAGE"
SENSOR_LIST_MESSAGE = "SENSOR_LIST_MESSAGE"
HELP_MESSAGE = "HELP_MESSAGE"
HELP_REPROMPT = "HELP_REPROMPT"
FALLBACK_MESSAGE = "FALLBACK_MESSAGE"
FALLBACK_REPROMPT = "FALLBACK_REPROMPT"
ERROR_MESSAGE = "ERROR_MESSAGE"
STOP_MESSAGE = "STOP_MESSAGE"
